version: '3'

services:
  api:
    image: nginx:1.23.1-alpine
    volumes:
      - ./apps/posts/build:/usr/share/nginx/html
    ports:
      - 8001:80

  web:
    image: node:20-alpine3.17
    environment:
      - API_BASE_URL=http://api
    volumes:
      - ./apps/web:/web
    working_dir: /web
    ports:
      - 3001:3000
    command: npm run dev